#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth 1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_MENTOHUST.*=.*/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT.*=.*/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS.*=.*/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y/g' .config #SS Plus
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SSSERVER.*=.*/CONFIG_FIRMWARE_INCLUDE_SSSERVER=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER.*=.*/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_ADBYBY.*=.*/CONFIG_FIRMWARE_INCLUDE_ADBYBY=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_FRPC.*=.*/CONFIG_FIRMWARE_INCLUDE_FRPC=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_FRPS.*=.*/CONFIG_FIRMWARE_INCLUDE_FRPS=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_TUNSAFE.*=.*/CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_ALIDDNS.*=.*/CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SMARTDNS.*=.*/CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_INCLUDE_SRELAY.*=.*/CONFIG_FIRMWARE_INCLUDE_SRELAY=n/g' .config    
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_USB.*=.*/CONFIG_FIRMWARE_ENABLE_USB=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_SERIAL.*=.*/CONFIG_FIRMWARE_ENABLE_SERIAL=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_AUDIO.*=.*/CONFIG_FIRMWARE_ENABLE_AUDIO=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_UFSD.*=.*/CONFIG_FIRMWARE_ENABLE_UFSD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_FAT.*=.*/CONFIG_FIRMWARE_ENABLE_FAT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_EXFAT.*=.*/CONFIG_FIRMWARE_ENABLE_EXFAT=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_EXT2.*=.*/CONFIG_FIRMWARE_ENABLE_EXT2=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_EXT3.*=.*/CONFIG_FIRMWARE_ENABLE_EXT3=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_FUSE.*=.*/CONFIG_FIRMWARE_ENABLE_FUSE=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_UVC.*=.*/CONFIG_FIRMWARE_ENABLE_UVC=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_LPRD.*=.*/CONFIG_FIRMWARE_ENABLE_LPRD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_U2EC.*=.*/CONFIG_FIRMWARE_ENABLE_U2EC=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_PARTED.*=.*/CONFIG_FIRMWARE_ENABLE_PARTED=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_SMBD.*=.*/CONFIG_FIRMWARE_ENABLE_SMBD=n/g' .config
        sed -i 's/.*CONFIG_FIRMWARE_ENABLE_SMBD36.*=.*/CONFIG_FIRMWARE_ENABLE_SMBD36=n/g' .config 
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=y" >> .config # simple-obfs混淆插件
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=y" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name: Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
